version: '3.8'

services:
  client:
    build: .
    ports:
      # We will expose the NGINX server as port 3001, so you will
      # be able to visit the front-end server at http://localhost:3001
      - "3001:3001"
