version: '3.8'

services:
  # spin up Postgres with vectors
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: turing
      POSTGRES_PASSWORD: turing
      POSTGRES_DB: demo
    ports:
      - "5435:5432"
